
import React from 'react';
import { Brain, ShoppingCart, Store, Utensils, Zap } from 'lucide-react';

const features = [
  {
    title: "AI Meal Planner",
    description: "Personalized weekly meal plans generated by AI based on your preferences, dietary goals, and health needs.",
    icon: Brain,
  },
  {
    title: "Swipeable Recipe Recommendations",
    description: "Like meal dating! Swipe through AI-recommended recipes and find the perfect match for your taste.",
    icon: Zap,
  },
  {
    title: "Smart Grocery Lists",
    description: "Automated grocery lists from your meal plan, optimized to minimize waste and save money.",
    icon: ShoppingCart,
  },
  {
    title: "Local Store Connection",
    description: "Connect with local grocery stores to order ingredients directly from your smart list.",
    icon: Store,
  },
  {
    title: "Nutrition Tracking",
    description: "Monitor your nutrient intake and calorie breakdown to meet your health goals.",
    icon: Utensils,
  },
];

const Features = () => {
  return (
    <section className="py-20 bg-white">
      <div className="container">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold mb-4">Smart Features for Healthier Eating</h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Gods Own Food combines AI technology with local grocery connections to make healthy eating simple and delicious.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className="p-6 border border-gray-200 rounded-lg hover:shadow-lg transition-all duration-300 hover:border-god-green"
            >
              <div className="h-12 w-12 bg-god-light-gray rounded-lg flex items-center justify-center mb-4">
                <feature.icon className="h-6 w-6 text-god-green" />
              </div>
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
