// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dchkgedaulfduxukfcgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjaGtnZWRhdWxmZHV4dWtmY2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTEzNzMsImV4cCI6MjA2OTI2NzM3M30.GO3X-zVl8W5W2rAdE9gUZX6_Y3M97jpWp-sQlgfXw1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});